import dotenv from 'dotenv';
import path from 'path';

// Load environment variables from the root .env file
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

import express from 'express';
import { testOpenAIRealtime, openaiRealtimeEngine } from './engines/openaiRealtimeEngine';
import { getBrainForEnvironment } from './brains/config';
import { routeToAgent } from './agents/agentRouter';
import { createDefaultContext, addToHistory } from './agents/types';

const app = express();
const port = 3000;

app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'aimee-backend' });
});

// OpenAI Realtime API test endpoint
app.post('/realtime-test', async (req, res) => {
  try {
    const { message, instructions } = req.body;

    if (!message || typeof message !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "message" field in request body'
      });
    }

    console.log('Processing realtime test request:', { message: message.substring(0, 100) + '...' });

    // Check if OpenAI is configured
    const status = openaiRealtimeEngine.getStatus();
    if (!status.configured) {
      return res.status(400).json({
        success: false,
        error: 'OpenAI Realtime API not configured. Set OPENAI_API_KEY environment variable.',
        brain: status.brain
      });
    }

    // Process the request through OpenAI Realtime API
    const result = await testOpenAIRealtime(message, instructions);

    if (result.success) {
      console.log('Realtime test successful, response length:', result.response?.length);
      res.json({
        success: true,
        response: result.response,
        sessionId: result.sessionId,
        brain: getBrainForEnvironment(),
        timestamp: new Date().toISOString()
      });
    } else {
      console.error('Realtime test failed:', result.error);
      res.status(500).json({
        success: false,
        error: result.error,
        brain: getBrainForEnvironment(),
        timestamp: new Date().toISOString()
      });
    }

  } catch (error) {
    console.error('Unexpected error in /realtime-test:', error);
    res.status(500).json({
      success: false,
      error: 'Internal server error during realtime test',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// Brain configuration status endpoint
app.get('/brain-status', (req, res) => {
  try {
    const brain = getBrainForEnvironment();
    const realtimeStatus = openaiRealtimeEngine.getStatus();

    res.json({
      currentBrain: brain,
      openaiRealtime: realtimeStatus,
      environment: process.env.NODE_ENV || 'development',
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('Error getting brain status:', error);
    res.status(500).json({
      error: 'Failed to get brain status',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// AImee Multi-Agent Chat Endpoint
app.post('/aimee-chat', async (req, res) => {
  try {
    const { userId, input, context: contextOverrides } = req.body;

    // Validate required fields
    if (!userId || typeof userId !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "userId" field in request body'
      });
    }

    if (!input || typeof input !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "input" field in request body'
      });
    }

    console.log('AImee Chat: Processing request for user:', userId);
    console.log('AImee Chat: Input:', input.substring(0, 100) + (input.length > 100 ? '...' : ''));

    // Build conversation context
    const context = createDefaultContext(userId, contextOverrides || {});

    // Add user input to conversation history
    const contextWithHistory = addToHistory(context, 'user', input);

    // Route to appropriate agent
    const result = await routeToAgent(input, contextWithHistory);

    // Add assistant response to history for next interactions
    const finalContext = addToHistory(contextWithHistory, 'assistant', result.text);

    console.log('AImee Chat: Response generated by', result.metadata?.routing?.selectedAgent || 'unknown agent');

    res.json({
      success: true,
      agent: result.metadata?.routing?.selectedAgent || result.metadata?.agent || 'unknown',
      response: result.text,
      metadata: {
        ...result.metadata,
        userId: userId,
        timestamp: new Date().toISOString(),
        conversationLength: finalContext.history.length
      }
    });

  } catch (error) {
    console.error('AImee Chat: Error processing request:', error);
    res.status(500).json({
      success: false,
      error: 'Internal server error during multi-agent processing',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// Agent testing endpoint (for debugging)
app.post('/aimee-chat/debug', async (req, res) => {
  try {
    const { userId, input, context: contextOverrides } = req.body;

    if (!userId || !input) {
      return res.status(400).json({
        error: 'Missing userId or input'
      });
    }

    const context = createDefaultContext(userId, contextOverrides || {});

    // Import router for debugging
    const { AgentRouter } = await import('./agents/agentRouter');
    const router = new AgentRouter();

    // Get debug information about agent matching
    const debugResults = await router.testAllAgents(input, context);

    res.json({
      input,
      userId,
      context,
      agentAnalysis: debugResults,
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('AImee Chat Debug: Error:', error);
    res.status(500).json({
      error: 'Debug analysis failed',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// AImee Arrival Endpoint - GPS-triggered location narratives
app.post('/aimee-arrival', async (req, res) => {
  try {
    const { userId, markerId, markerName, location, mode } = req.body;

    // Validate required fields
    if (!userId || typeof userId !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "userId" field in request body'
      });
    }

    if (!markerId || typeof markerId !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "markerId" field in request body'
      });
    }

    if (!markerName || typeof markerName !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "markerName" field in request body'
      });
    }

    if (!location || typeof location.lat !== 'number' || typeof location.lng !== 'number') {
      return res.status(400).json({
        success: false,
        error: 'Missing or invalid "location" field with lat/lng coordinates'
      });
    }

    console.log('AImee Arrival: Processing arrival at marker:', markerName);
    console.log('AImee Arrival: User:', userId, 'Location:', location, 'Mode:', mode);

    // Build conversation context for arrival
    const context = createDefaultContext(userId, {
      location: {
        lat: location.lat,
        lng: location.lng,
        nearestMarkerId: markerId
      },
      tourState: {
        currentMarkerId: markerId,
        mode: mode || 'drive'
      },
      preferences: {
        verbosity: 'medium',
        tone: 'conversational'
      }
    });

    // Construct arrival-specific input prompt
    const arrivalInput = `We just arrived at the marker "${markerName}". Please provide an engaging arrival narrative about this place. Share interesting details, history, or recommendations that would enhance the visitor's experience here.`;

    // Route through the multi-agent system
    const result = await routeToAgent(arrivalInput, context);

    console.log('AImee Arrival: Narrative generated by', result.metadata?.routing?.selectedAgent || 'unknown agent');

    res.json({
      success: true,
      markerId,
      markerName,
      agent: result.metadata?.routing?.selectedAgent || result.metadata?.agent || 'unknown',
      response: result.text,
      metadata: {
        ...result.metadata,
        userId,
        markerId,
        location,
        mode: mode || 'drive',
        timestamp: new Date().toISOString(),
        arrivalType: 'gps_triggered'
      }
    });

  } catch (error) {
    console.error('AImee Arrival: Error processing arrival request:', error);
    res.status(500).json({
      success: false,
      error: 'Internal server error during arrival processing',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

app.listen(port, () => {
  console.log(`AImee Backend running on port ${port}`);
  console.log('Available endpoints:');
  console.log('  GET  /health - Health check');
  console.log('  POST /realtime-test - Test OpenAI Realtime API');
  console.log('  GET  /brain-status - Brain configuration status');
  console.log('  POST /aimee-chat - Multi-agent conversation endpoint');
  console.log('  POST /aimee-chat/debug - Agent routing debug information');
  console.log('  POST /aimee-arrival - GPS-triggered arrival narratives');

  // Log brain configuration on startup
  try {
    const brain = getBrainForEnvironment();
    const realtimeStatus = openaiRealtimeEngine.getStatus();
    console.log('Current brain configuration:', brain.name, `(${brain.provider})`);
    console.log('OpenAI Realtime configured:', realtimeStatus.configured);
  } catch (error) {
    console.warn('Could not determine brain configuration on startup:', error);
  }
});